import type { Products } from "../contexts/AppDataContext";
import img from "../assets/LIV-UNBOTHERED.jpg";

export const MOCK_DATA: Products = [
	{
		_id: "01JYYZD2J6Q8FGYGAZXEZQBYGM",
		name: "Stylish T-Shirt",
		description: "Stylish t-shirt with custom design.",
		price: 24.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2025-03-10T17:42:28Z",
		bestseller: true,
	},
	{
		_id: "01JYYZD2J75BP8JDW2ANY9T84A",
		name: "Stylish T-Shirt 2",
		description: "Stylish t-shirt with custom design.",
		price: 34.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2025-05-21T13:05:47Z",
		bestseller: true,
	},
	{
		_id: "01JYYZD2J8N5HRDVKC0PHXTR8H",
		name: "Stylish Laptop Backpack",
		description: "Water-resistant laptop backpack with multiple compartments.",
		price: 69.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Accessories",
		sizes: ["S", "M", "L", "XL"],
		date: "2025-05-10T02:07:47Z",
		bestseller: false,
	},
	{
		_id: "01JYYZD2J9JFYXKTWJMB8VKMAN",
		name: "Stylish Oversized T-Shirt",
		description: "Stylish oversized t-shirt with custom design.",
		price: 38.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2024-12-25T14:47:50Z",
		bestseller: false,
	},
	{
		_id: "01JYYZD2JAW1VN933GTN507CGJ",
		name: "Stylish Hoodie",
		description: "Stylish hoodie with custom design.",
		price: 52.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2024-08-27T17:26:37Z",
		bestseller: true,
	},
	{
		_id: "01JYYZD2J6Q8FGYGAZXEZQBYG3",
		name: "Stylish T-Shirt 3",
		description: "Stylish t-shirt with custom design.",
		price: 22.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2025-03-10T17:42:28Z",
		bestseller: false,
	},
	{
		_id: "01JYYZD2J75BP8JDW2ANY9T844",
		name: "Stylish T-Shirt 4",
		description: "Stylish t-shirt with custom design.",
		price: 39.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2025-05-21T13:05:47Z",
		bestseller: true,
	},
	{
		_id: "01JYYZD2J8N5HRDVKC0PHXTR82",
		name: "Stylish Backpack 2",
		description: "Water-resistant laptop backpack with multiple compartments.",
		price: 79.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Accessories",
		sizes: ["S", "M", "L", "XL"],
		date: "2025-05-10T02:07:47Z",
		bestseller: false,
	},
	{
		_id: "01JYYZD2J9JFYXKTWJMB8VKMA2",
		name: "Stylish Oversized T-Shirt 2",
		description: "Stylish oversized t-shirt with custom design.",
		price: 27.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2024-12-25T14:47:50Z",
		bestseller: true,
	},
	{
		_id: "01JYYZD2JAW1VN933GTN507CG2",
		name: "Stylish Hoodie 2",
		description: "Stylish hoodie with custom design.",
		price: 44.99,
		image: [`${img}`, `${img}`, `${img}`, `${img}`],
		category: "Men, Women",
		subcategory: "Topwear",
		sizes: ["S", "M", "L", "XL"],
		date: "2024-08-27T17:26:37Z",
		bestseller: false,
	},
];
