name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-cd:
    name: Test - Build - Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["18.x", "20.x"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies (client)
        working-directory: frontend
        run: npm ci

      - name: Run Tests (client)
        working-directory: frontend
        run: npm run test

      - name: Install dependencies (server)
        working-directory: backend
        run: npm ci

      - name: Run Tests (server)
        working-directory: backend
        run: npm run test

      - name: Build Frontend
        working-directory: frontend
        run: npm run build
